### PR TITLE
Add get with basic auth

### PR DESCRIPTION
**Pull request by igreenfield**

### CODE REVIEW

**Comment by igreenfield** [comment]
@jniesen could you please let me know what the problem? I can't reproduce this issue in my env.

**Comment by jniesen** [comment]
@igreenfield Nothing in the build environment is providing an HttpGet class. Is it possible that something in your local development environment is adding that to your CLASSPATH?

**Comment by igreenfield** [comment]
@jniesen The only missing part was the import in the head of the groovy file. so now it is OK. thanks

**Comment by igreenfield** [comment]
@jniesen What you think about merging this?

**Comment by jniesen** [comment]
@igreenfield Sorry, I lost track of this. Looks good. Thank you.

**Comment by jniesen** [comment]
@igreenfield Findbugs is reporting some issues while building a release. I'm going to address those and then create an HPI for 0.0.4. It'll show up on the [releases](https://github.com/jniesen/build-flow-http-extension/releases) page at some point today.

**Comment by igreenfield** [comment]
@jniesen thank!!!

**Comment by jniesen** [comment]
@igreenfield https://github.com/jniesen/build-flow-http-extension/releases/tag/v0.0.4

Thank you again for the contribution.

**Pull request merged**
